/**
 * Gateway Bloque 2 copy defaults: P5, P6, Micro-espejo 2, P7, P8.
 * Extracted from: gateway-bloque2-data.ts
 */

import type { CopySection } from './types'

export function getGatewayBloque2Defaults(): CopySection[] {
  return [
    // ── P5 — Alegría de vivir ────────────────────────────────────────
    {
      id: 'gateway.p5.optionA',
      section: 'gateway',
      subsection: 'p5',
      label: 'P5 opción A — No lo recuerdo',
      defaultValue: '\u201cNo lo recuerdo\u201d',
      fieldType: 'short',
      hint: 'Opciones sobre la última vez que disfrutó algo sin culpa.',
    },
    {
      id: 'gateway.p5.optionB',
      section: 'gateway',
      subsection: 'p5',
      label: 'P5 opción B — Hace semanas o meses',
      defaultValue: '\u201cHace semanas o meses\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p5.optionC.title',
      section: 'gateway',
      subsection: 'p5',
      label: 'P5 opción C — título',
      defaultValue: '\u201cPuedo, pero no suelto la cabeza\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p5.optionC.subtitle',
      section: 'gateway',
      subsection: 'p5',
      label: 'P5 opción C — subtítulo',
      defaultValue: 'Disfrutas pero no del todo — algo te tira de vuelta',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p5.optionD.title',
      section: 'gateway',
      subsection: 'p5',
      label: 'P5 opción D — título',
      defaultValue: '\u201cDisfruto con culpa\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p5.optionD.subtitle',
      section: 'gateway',
      subsection: 'p5',
      label: 'P5 opción D — subtítulo',
      defaultValue: 'Sientes que deberías estar haciendo algo productivo',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p5.optionE',
      section: 'gateway',
      subsection: 'p5',
      label: 'P5 opción E — Disfruto con frecuencia',
      defaultValue: '\u201cDisfruto con frecuencia\u201d',
      fieldType: 'short',
    },

    // ── P6 — Frase identitaria ───────────────────────────────────────
    {
      id: 'gateway.p6.optionA.title',
      section: 'gateway',
      subsection: 'p6',
      label: 'P6 — No puedo parar (título)',
      defaultValue: '\u201cNo puedo parar\u201d',
      fieldType: 'short',
      hint: 'La pregunta más importante del gateway. Define el arquetipo.',
    },
    {
      id: 'gateway.p6.optionA.subtitle',
      section: 'gateway',
      subsection: 'p6',
      label: 'P6 — No puedo parar (subtítulo)',
      defaultValue: 'Sientes que si aflojas, todo lo que has construido se cae',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p6.optionB.title',
      section: 'gateway',
      subsection: 'p6',
      label: 'P6 — Puedo con todo (título)',
      defaultValue: '\u201cPuedo con todo\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p6.optionB.subtitle',
      section: 'gateway',
      subsection: 'p6',
      label: 'P6 — Puedo con todo (subtítulo)',
      defaultValue: 'No necesitas ayuda — o eso es lo que repites',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p6.optionC.title',
      section: 'gateway',
      subsection: 'p6',
      label: 'P6 — Si yo caigo, todos caen (título)',
      defaultValue: '\u201cSi yo caigo, todos caen\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p6.optionC.subtitle',
      section: 'gateway',
      subsection: 'p6',
      label: 'P6 — Si yo caigo, todos caen (subtítulo)',
      defaultValue: 'Las personas que dependen de ti te mantienen en pie — y agotado',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p6.optionD.title',
      section: 'gateway',
      subsection: 'p6',
      label: 'P6 — Necesito entender primero (título)',
      defaultValue: '\u201cNecesito entender primero\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p6.optionD.subtitle',
      section: 'gateway',
      subsection: 'p6',
      label: 'P6 — Necesito entender primero (subtítulo)',
      defaultValue: 'No actúas hasta que lo tienes todo claro — y nunca está del todo claro',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p6.optionE.title',
      section: 'gateway',
      subsection: 'p6',
      label: 'P6 — He probado de todo (título)',
      defaultValue: '\u201cHe probado de todo\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p6.optionE.subtitle',
      section: 'gateway',
      subsection: 'p6',
      label: 'P6 — He probado de todo (subtítulo)',
      defaultValue: 'Nada ha funcionado de verdad y empiezas a dudar de que algo pueda',
      fieldType: 'medium',
    },

    // ── MICRO-ESPEJO 2 — variantes por P6 ────────────────────────────
    {
      id: 'gateway.microespejo2.A.text',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 — No puedo parar',
      defaultValue: 'Llevas años confundiendo resistencia con fortaleza. Tu cuerpo te pide parar pero tu miedo te dice que no puedes. Y ese miedo no es irracional — es la respuesta de un sistema nervioso que lleva tanto tiempo en emergencia que ya no sabe funcionar de otra forma. No necesitas parar. Necesitas regularte para que tu rendimiento no dependa de tu desgaste.',
      fieldType: 'long',
      hint: 'Reflexión para P6=A. La más larga y personalizada del gateway.',
    },
    {
      id: 'gateway.microespejo2.A.collective',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 A — dato colectivo',
      defaultValue: 'El 91% de personas que seleccionan esta frase llevan más de 2 años con su sistema nervioso en modo alarma sin saberlo. Los que regularon su biología no pararon — rindieron mejor.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo2.B.text',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 — Puedo con todo',
      defaultValue: 'Poder con todo tiene un precio que nadie ve — ni siquiera tú. Tu cuerpo lleva la cuenta aunque tu mente la ignore. No te estamos pidiendo que admitas debilidad. Te estamos mostrando datos. Y los datos dicen que tu sistema nervioso está sosteniendo un nivel de alerta que tiene fecha de caducidad.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo2.B.collective',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 B — dato colectivo',
      defaultValue: 'El 87% de las personas que responden "puedo con todo" presentan señales biológicas que contradicen su percepción. No es fortaleza — es un sistema nervioso que ya no puede enviar la señal de alarma porque la alarma lleva años encendida.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo2.C.text',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 — Si yo caigo',
      defaultValue: 'Has convertido el cuidado de los demás en tu razón de existir — y tu propio cuidado en un lujo que no te permites. Pero la biología no entiende de sacrificios: tu cuerpo se desgasta igual cuides de quien cuides. Y cuando se desgasta el que sostiene todo... todo lo que sostienes se cae.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo2.C.collective',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 C — dato colectivo',
      defaultValue: 'El 84% de personas con tu patrón reportan que la culpa de cuidarse es mayor que el malestar de no hacerlo. Es la trampa más silenciosa del agotamiento.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo2.D.text',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 — Necesito entender',
      defaultValue: 'Entender es tu forma de sentirte seguro. Pero hay un punto donde entender más se convierte en la excusa perfecta para no actuar — porque actuar implica soltar el control. Lo que tu sistema nervioso necesita no es más análisis. Es una intervención concreta, medible y reversible.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo2.D.collective',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 D — dato colectivo',
      defaultValue: 'El 79% de personas que priorizan entender antes de actuar tardan una media de 14 meses más en resolver su situación. No por falta de información — por exceso de análisis.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo2.E.text',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 — He probado de todo',
      defaultValue: 'No es que nada funcione. Es que nadie ha mirado el cuadro completo. Un psicólogo trabaja la mente pero no tiene acceso a tu bioquímica. Un médico mira analíticas estándar que no miden lo que importa. Un coach te da herramientas que tu cerebro no puede ejecutar. Lo que falta no es otro intento — es un abordaje que integre todo.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo2.E.collective',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 E — dato colectivo',
      defaultValue: 'El 72% de las personas que llegan al programa han probado 3 o más enfoques previos. El factor común: ninguno abordó la biología como punto de partida.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo2.default.text',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 — fallback',
      defaultValue: 'Tu sistema nervioso lleva tanto tiempo en modo supervivencia que ya no distingue emergencia real de vida cotidiana. Lo que sientes no es un defecto — es la respuesta predecible de un sistema que no ha descansado de verdad en mucho tiempo.',
      fieldType: 'long',
      hint: 'Se usa cuando P6 no tiene variante específica.',
    },
    {
      id: 'gateway.microespejo2.default.collective',
      section: 'gateway',
      subsection: 'microespejo2',
      label: 'Micro-espejo 2 — fallback dato colectivo',
      defaultValue: 'El 85% de personas con un patrón similar al tuyo llevan más de 2 años con su sistema nervioso en modo alarma sin saberlo. La biología no miente — y la tuya está pidiendo un cambio.',
      fieldType: 'long',
    },

    // ── P7 — Sliders ────────────────────────────────────────────────
    {
      id: 'gateway.p7.slider1',
      section: 'gateway',
      subsection: 'p7',
      label: 'P7 slider 1 — Regulación',
      defaultValue: 'Capacidad de descansar y desconectar',
      fieldType: 'short',
      hint: 'Etiqueta del primer slider. Auto-evaluación subjetiva 1-10.',
    },
    {
      id: 'gateway.p7.slider2',
      section: 'gateway',
      subsection: 'p7',
      label: 'P7 slider 2 — Sueño',
      defaultValue: 'Calidad de tu sueño',
      fieldType: 'short',
    },
    {
      id: 'gateway.p7.slider3',
      section: 'gateway',
      subsection: 'p7',
      label: 'P7 slider 3 — Claridad',
      defaultValue: 'Claridad para pensar y decidir',
      fieldType: 'short',
    },
    {
      id: 'gateway.p7.slider4',
      section: 'gateway',
      subsection: 'p7',
      label: 'P7 slider 4 — Emocional',
      defaultValue: 'Estabilidad emocional',
      fieldType: 'short',
    },
    {
      id: 'gateway.p7.slider5',
      section: 'gateway',
      subsection: 'p7',
      label: 'P7 slider 5 — Alegría',
      defaultValue: 'Ilusión por lo que haces',
      fieldType: 'short',
    },

    // ── P8 — Duración ───────────────────────────────────────────────
    {
      id: 'gateway.p8.optionA',
      section: 'gateway',
      subsection: 'p8',
      label: 'P8 opción A — Semanas',
      defaultValue: '\u201cSemanas\u201d',
      fieldType: 'short',
      hint: '¿Cuánto tiempo llevas así? Opciones de duración.',
    },
    {
      id: 'gateway.p8.optionB',
      section: 'gateway',
      subsection: 'p8',
      label: 'P8 opción B — Meses',
      defaultValue: '\u201cMeses\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p8.optionC',
      section: 'gateway',
      subsection: 'p8',
      label: 'P8 opción C — Más de un año',
      defaultValue: '\u201cMás de un año\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p8.optionD',
      section: 'gateway',
      subsection: 'p8',
      label: 'P8 opción D — Años',
      defaultValue: '\u201cAños — no recuerdo estar bien\u201d',
      fieldType: 'short',
    },
  ]
}
