/**
 * Gateway Bloque 1 copy defaults: P1, P2, P3, P4, Primera Verdad, Micro-espejo 1.
 * Extracted from: P1Cards.tsx, gateway-bloque1-data.ts
 */

import type { CopySection } from './types'

export function getGatewayBloque1Defaults(): CopySection[] {
  return [
    // ── P1 — ¿Qué te trajo hasta aquí? ──────────────────────────────
    {
      id: 'gateway.p1.question',
      section: 'gateway',
      subsection: 'p1',
      label: 'Pregunta P1',
      defaultValue: '¿Qué te trajo hasta aquí?',
      fieldType: 'short',
      hint: 'Pregunta principal del hero. Es lo primero que ve la persona.',
    },
    {
      id: 'gateway.p1.optionA.title',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción A — título',
      defaultValue: '\u201cAgotamiento que no se va\u201d',
      fieldType: 'short',
      hint: 'Primera opción de P1. Perfil: Productivo Colapsado.',
    },
    {
      id: 'gateway.p1.optionA.subtitle',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción A — subtítulo',
      defaultValue: 'Llevas tiempo sintiéndote agotado y nada de lo que haces lo resuelve',
      fieldType: 'medium',
      hint: 'Texto explicativo debajo de "Agotamiento que no se va".',
    },
    {
      id: 'gateway.p1.optionB.title',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción B — título',
      defaultValue: '\u201cRendimiento en caída\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p1.optionB.subtitle',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción B — subtítulo',
      defaultValue: 'Tu capacidad ha bajado y no entiendes por qué',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p1.optionC.title',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción C — título',
      defaultValue: '\u201cEl cuerpo habla\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p1.optionC.subtitle',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción C — subtítulo',
      defaultValue: 'Duermes mal, estás irritable, y tu cuerpo da señales que no puedes ignorar',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p1.optionD.title',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción D — título',
      defaultValue: '\u201cAlguien me lo sugirió\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p1.optionD.subtitle',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción D — subtítulo',
      defaultValue: 'Un médico, terapeuta o alguien de confianza te recomendó explorar esto',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p1.optionE.title',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción E — título',
      defaultValue: '\u201cCuriosidad\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p1.optionE.subtitle',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción E — subtítulo',
      defaultValue: 'Quieres saber cómo está tu sistema nervioso',
      fieldType: 'medium',
    },

    // ── P2 — Sueño ──────────────────────────────────────────────────
    {
      id: 'gateway.p2.optionA',
      section: 'gateway',
      subsection: 'p2',
      label: 'P2 opción A — mente no se apaga',
      defaultValue: '\u201cMe cuesta dormirme — mi mente no se apaga\u201d',
      fieldType: 'short',
      hint: 'Opciones de sueño. Cada opción aparece como card seleccionable.',
    },
    {
      id: 'gateway.p2.optionB',
      section: 'gateway',
      subsection: 'p2',
      label: 'P2 opción B — despertar nocturno',
      defaultValue: '\u201cMe despierto a las 3-4 de la mañana y no puedo volver a dormirme\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p2.optionC',
      section: 'gateway',
      subsection: 'p2',
      label: 'P2 opción C — sueño no reparador',
      defaultValue: '\u201cDuermo horas pero me despierto igual de cansado\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p2.optionD',
      section: 'gateway',
      subsection: 'p2',
      label: 'P2 opción D — poco sueño funcional',
      defaultValue: '\u201cDuermo poco pero funciono\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p2.optionE',
      section: 'gateway',
      subsection: 'p2',
      label: 'P2 opción E — sueño bueno',
      defaultValue: '\u201cMi sueño es razonablemente bueno\u201d',
      fieldType: 'short',
    },

    // ── P3 — Síntomas cognitivos (selección múltiple) ────────────────
    {
      id: 'gateway.p3.niebla.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Niebla mental (título)',
      defaultValue: '\u201cNiebla mental\u201d',
      fieldType: 'short',
      hint: 'P3 es selección múltiple. Cada opción tiene título + subtítulo.',
    },
    {
      id: 'gateway.p3.niebla.subtitle',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Niebla mental (subtítulo)',
      defaultValue: 'Leo algo y al terminar no sé qué he leído',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p3.decisiones.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Peores decisiones (título)',
      defaultValue: '\u201cPeores decisiones\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p3.decisiones.subtitle',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Peores decisiones (subtítulo)',
      defaultValue: 'Tomo peores decisiones que antes — y lo noto',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p3.dispersa.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Mente dispersa (título)',
      defaultValue: '\u201cMente dispersa\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p3.dispersa.subtitle',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Mente dispersa (subtítulo)',
      defaultValue: 'Mi cabeza salta de un tema a otro sin control',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p3.palabras.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Palabras perdidas (título)',
      defaultValue: '\u201cPalabras perdidas\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p3.palabras.subtitle',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Palabras perdidas (subtítulo)',
      defaultValue: 'Me cuesta encontrar palabras que antes tenía',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p3.decisional.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Agotamiento decisional (título)',
      defaultValue: '\u201cAgotamiento decisional\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p3.decisional.subtitle',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Agotamiento decisional (subtítulo)',
      defaultValue: 'Al final del día no puedo elegir ni qué cenar',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p3.ninguna.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Ninguna de estas',
      defaultValue: '\u201cNinguna de estas\u201d',
      fieldType: 'short',
    },

    // ── P4 — Síntomas emocionales ────────────────────────────────────
    {
      id: 'gateway.p4.optionA.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Irritabilidad (título)',
      defaultValue: '\u201cIrritabilidad\u201d',
      fieldType: 'short',
      hint: 'Opciones emocionales. Cada una con título + subtítulo explicativo.',
    },
    {
      id: 'gateway.p4.optionA.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Irritabilidad (subtítulo)',
      defaultValue: 'Te encienden cosas que antes no te afectaban',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p4.optionB.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Vacío (título)',
      defaultValue: '\u201cVacío\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p4.optionB.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Vacío (subtítulo)',
      defaultValue: 'Sientes un hueco que no sabes describir aunque desde fuera todo va bien',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p4.optionC.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Explosiones de culpa (título)',
      defaultValue: '\u201cExplosiones de culpa\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p4.optionC.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Explosiones de culpa (subtítulo)',
      defaultValue: 'Explotas con quien más quieres y después te sientes fatal',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p4.optionD.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Anestesia emocional (título)',
      defaultValue: '\u201cAnestesia emocional\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p4.optionD.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Anestesia emocional (subtítulo)',
      defaultValue: 'No sientes nada — ni alegría ni tristeza. Como si estuvieras apagado',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p4.optionE.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Rumiación constante (título)',
      defaultValue: '\u201cRumiación constante\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p4.optionE.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Rumiación constante (subtítulo)',
      defaultValue: 'Tu mente no para: conversaciones, errores, escenarios futuros',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p4.optionF.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Razonablemente bien (título)',
      defaultValue: '\u201cRazonablemente bien\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p4.optionF.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Razonablemente bien (subtítulo)',
      defaultValue: 'Tu equilibrio emocional es aceptable',
      fieldType: 'medium',
    },

    // ── PRIMERA VERDAD — combinaciones P1×P2 ─────────────────────────
    {
      id: 'gateway.primeraverdad.AA.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad A-A — texto',
      defaultValue: 'Tu agotamiento no es cansancio normal. Tu mente no se apaga por la noche porque tu sistema nervioso no distingue descanso de amenaza.',
      fieldType: 'long',
      hint: 'Combinación: Agotamiento + Mente no se apaga. Texto personalizado de reflexión.',
    },
    {
      id: 'gateway.primeraverdad.AA.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad A-A — dato colectivo',
      defaultValue: 'El 78% de los +25.000 sistemas nerviosos analizados con tu patrón de respuestas presentan niveles de la hormona del estrés crónicamente elevados. No es falta de voluntad — es bioquímica.',
      fieldType: 'long',
      hint: 'Dato colectivo que aparece debajo del texto de la Primera Verdad.',
    },
    {
      id: 'gateway.primeraverdad.AB.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad A-B — texto',
      defaultValue: 'Tu agotamiento no es cansancio normal. Tu cortisol se dispara de noche porque tu sistema no distingue descanso de amenaza.',
      fieldType: 'long',
      hint: 'Combinación: Agotamiento + Despertar nocturno.',
    },
    {
      id: 'gateway.primeraverdad.AB.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad A-B — dato colectivo',
      defaultValue: 'El 82% de los +25.000 sistemas nerviosos analizados con tu patrón de respuestas presentan niveles de la hormona del estrés crónicamente elevados. No es falta de voluntad — es bioquímica.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.BA.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad B-A — texto',
      defaultValue: 'Tu rendimiento bajó porque tu cerebro no descansa. Sin sueño profundo, el prefrontal no puede tomar decisiones con la precisión que antes tenías.',
      fieldType: 'long',
      hint: 'Combinación: Rendimiento en caída + Mente no se apaga.',
    },
    {
      id: 'gateway.primeraverdad.BA.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad B-A — dato colectivo',
      defaultValue: 'El 71% de ejecutivos con deterioro cognitivo progresivo reportan un patrón de sueño idéntico al tuyo como factor previo. La conexión es directa y reversible.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.CB.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad C-B — texto',
      defaultValue: 'Tu cuerpo te está dando señales que tu mente ha intentado ignorar. El despertar nocturno es la más clara — y la que más información contiene.',
      fieldType: 'long',
      hint: 'Combinación: El cuerpo habla + Despertar nocturno.',
    },
    {
      id: 'gateway.primeraverdad.CB.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad C-B — dato colectivo',
      defaultValue: 'El 82% de personas con señales físicas persistentes y despertar nocturno muestran activación crónica del sistema de alerta. El cuerpo habló antes que la mente.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.CC.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad C-C — texto',
      defaultValue: 'Tu cuerpo te está dando señales que tu mente ha intentado ignorar. El cansancio que no se va con sueño es la más clara — y la que más información contiene.',
      fieldType: 'long',
      hint: 'Combinación: El cuerpo habla + Sueño no reparador.',
    },
    {
      id: 'gateway.primeraverdad.CC.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad C-C — dato colectivo',
      defaultValue: 'El 85% de personas con señales físicas persistentes y sueño no reparador muestran activación crónica del sistema de alerta. El cuerpo habló antes que la mente.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.D.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad D (derivado) — texto',
      defaultValue: 'Alguien que te conoce vio algo que tú llevas tiempo normalizando. Tu sistema nervioso confirma que tenía razón.',
      fieldType: 'long',
      hint: 'Para P1=D (Alguien me lo sugirió). Independiente de P2.',
    },
    {
      id: 'gateway.primeraverdad.D.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad D — dato colectivo',
      defaultValue: 'El 69% de personas derivadas por un profesional presentan un nivel de agotamiento que ya habían normalizado completamente. El entorno siempre lo detecta antes.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.ED.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad E-D — texto',
      defaultValue: 'Dices que funcionas con poco sueño. Tu sistema nervioso puede tener una versión diferente de esa historia.',
      fieldType: 'long',
      hint: 'Combinación: Curiosidad + Duermo poco pero funciono.',
    },
    {
      id: 'gateway.primeraverdad.ED.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad E-D — dato colectivo',
      defaultValue: 'El 74% de personas que declaran "funcionar con poco sueño" muestran marcadores de déficit cognitivo acumulado que no perciben subjetivamente. El umbral se mueve — lo que antes era cansancio ya no lo registras como tal.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.default.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad — fallback por defecto',
      defaultValue: 'Tu sistema nervioso lleva tiempo funcionando en modo de emergencia. Lo que sientes no es debilidad — es el resultado predecible de un sistema que no ha descansado de verdad.',
      fieldType: 'long',
      hint: 'Se usa cuando la combinación P1×P2 no tiene texto específico.',
    },
    {
      id: 'gateway.primeraverdad.default.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad — dato colectivo fallback',
      defaultValue: 'El 73% de los +25.000 sistemas nerviosos analizados con un patrón similar al tuyo presentan marcadores de estrés crónico. No es falta de voluntad — es bioquímica.',
      fieldType: 'long',
    },

    // ── MICRO-ESPEJO 1 — variantes P3×P4 ─────────────────────────────
    {
      id: 'gateway.microespejo1.pocoB.text',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — pocos síntomas + Vacío',
      defaultValue: 'Tu cerebro funciona pero por dentro hay un vacío. No es tristeza — es un sistema nervioso que se ha apagado para protegerte. Como un fusible que salta.',
      fieldType: 'long',
      hint: 'Pocas señales cognitivas + P4=Vacío. Texto de reflexión personalizado.',
    },
    {
      id: 'gateway.microespejo1.pocoB.collective',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — pocoB dato colectivo',
      defaultValue: 'El 68% de personas con tu combinación no identifican esto como agotamiento. Lo viven como ausencia sin causa. Tiene causa — y tiene solución.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo1.muchoC.text',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — muchos síntomas + Explosiones',
      defaultValue: 'Das todo lo que tienes a los demás y lo que queda para ti no alcanza. Tu cerebro no tiene recursos para regularse después de regularte a ti — y el resultado es que explotas justo con quien menos quieres.',
      fieldType: 'long',
      hint: 'Muchas señales cognitivas + P4=Explosiones de culpa.',
    },
    {
      id: 'gateway.microespejo1.muchoC.collective',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — muchoC dato colectivo',
      defaultValue: 'El 79% de personas con tu patrón sienten culpa después de las explosiones. Esa culpa también agota. Es un ciclo — no un defecto de carácter.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo1.muchoD.text',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — muchos síntomas + Anestesia',
      defaultValue: 'Tu cuerpo ha encontrado la forma más radical de protegerte: apagar los circuitos. No es que no te importe — es que sentir se volvió demasiado costoso para tu sistema.',
      fieldType: 'long',
      hint: 'Muchas señales cognitivas + P4=Anestesia emocional.',
    },
    {
      id: 'gateway.microespejo1.muchoD.collective',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — muchoD dato colectivo',
      defaultValue: 'El 74% de personas con anestesia emocional tardan más de 2 años en identificar lo que les ocurre. Tú lo estás nombrando hoy.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo1.pocoE.text',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — pocos síntomas + Rumiación',
      defaultValue: 'Tu capacidad cognitiva está intacta pero tu mente la usa para anticipar en lugar de ejecutar. No estás pensando — estás sobreviviendo mentalmente.',
      fieldType: 'long',
      hint: 'Pocas señales cognitivas + P4=Rumiación constante.',
    },
    {
      id: 'gateway.microespejo1.pocoE.collective',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — pocoE dato colectivo',
      defaultValue: 'El 73% de personas con rumiación activa y pocas señales cognitivas tienen el sistema nervioso en hipervigilancia constante. La amenaza que monitoriza no existe — pero el sistema actúa como si sí.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo1.default.text',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — fallback',
      defaultValue: 'Tu cabeza va a mil pero tu capacidad de procesar se ha reducido. No es que seas menos capaz — es que tu cerebro está usando su energía para mantenerte en alerta en lugar de para pensar con claridad. Y eso tiene una consecuencia directa: te irritas más porque tu freno interno está agotado.',
      fieldType: 'long',
      hint: 'Se usa cuando la combinación P3×P4 no tiene variante específica.',
    },
    {
      id: 'gateway.microespejo1.default.collective',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — fallback dato colectivo',
      defaultValue: 'El 65% de personas con tu combinación de respuestas no saben que la irritabilidad y la niebla mental tienen la misma causa. Cuando se regula una, la otra mejora.',
      fieldType: 'long',
    },
  ]
}
