/**
 * Mapa Vivo copy defaults.
 * Extracted from: FocusBanner, EvolutionTimeline, EvolutionSession,
 * AspiracionalTimeline, LeadDimensions.
 */

import type { CopySection } from './types'

export function getMapaDefaults(): CopySection[] {
  return [
    // ── FOCUS BANNER — NEW states ────────────────────────────────────
    {
      id: 'mapa.focus.new.archetype.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Arquetipo nuevo (tag)',
      defaultValue: 'NUEVO DESDE TU ÚLTIMA VISITA',
      fieldType: 'short',
      hint: 'Tag que aparece cuando el arquetipo se desbloquea por primera vez.',
    },
    {
      id: 'mapa.focus.new.archetype.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Arquetipo nuevo (CTA)',
      defaultValue: 'Descubrir tu perfil completo',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.insightD7.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Insight D7 nuevo (tag)',
      defaultValue: 'TU MAPA SE HA ACTUALIZADO',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.insightD7.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Insight D7 nuevo (CTA)',
      defaultValue: 'Ver tu evaluación completa',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.session.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Sesión nueva (tag)',
      defaultValue: 'DISPONIBLE',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.session.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Sesión nueva (título)',
      defaultValue: 'Tu sesión con Javier',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.session.description',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Sesión nueva (descripción)',
      defaultValue: 'Ya tiene tu mapa. La sesión arranca desde tus datos, no desde cero. 20 min gratuitos. Sin compromiso.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.focus.new.session.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Sesión nueva (CTA)',
      defaultValue: 'Elegir horario',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.subdimensions.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Subdimensiones nuevas (tag)',
      defaultValue: 'PROFUNDIZA TU EVALUACIÓN',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.subdimensions.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Subdimensiones nuevas (CTA)',
      defaultValue: 'Responder ahora',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.book.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Libro nuevo (tag)',
      defaultValue: 'PARA TI',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.book.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Libro nuevo (título)',
      defaultValue: 'Un capítulo escrito para tu patrón',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.book.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Libro nuevo (CTA)',
      defaultValue: 'Leer extracto',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.reevaluation.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación nueva (título)',
      defaultValue: '¿Ha cambiado algo en tu regulación?',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.reevaluation.description',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación nueva (descripción)',
      defaultValue: 'Responde las mismas 10 preguntas y compara con tu día 0.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.focus.new.reevaluation.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación nueva (CTA)',
      defaultValue: 'Reevaluar mi estado',
      fieldType: 'short',
    },

    // ── FOCUS BANNER — PENDING states ────────────────────────────────
    {
      id: 'mapa.focus.pending.session.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Sesión pendiente (tag)',
      defaultValue: 'PENDIENTE',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.session.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Sesión pendiente (título)',
      defaultValue: 'Tu sesión con Javier',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.session.description',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Sesión pendiente (descripción)',
      defaultValue: 'Aún no has reservado tu sesión gratuita de 20 minutos. Javier ya tiene tu mapa.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.focus.pending.subdimensions.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Subdimensiones pendientes (tag)',
      defaultValue: 'PENDIENTE',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.subdimensions.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Subdimensiones pendientes (título)',
      defaultValue: 'Profundiza tu evaluación',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.reevaluation.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación disponible (tag)',
      defaultValue: 'DISPONIBLE',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.reevaluation.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación disponible (título)',
      defaultValue: 'Tu reevaluación está lista',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.reevaluation.description',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación disponible (descripción)',
      defaultValue: 'Compara tu estado actual con tu día 0. Verás cuánto ha cambiado.',
      fieldType: 'medium',
    },

    // ── FOCUS BANNER — TEASER (no pagado) ────────────────────────────
    {
      id: 'mapa.focus.teaser.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Teaser no pagado (tag)',
      defaultValue: 'TU SIGUIENTE PASO',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.teaser.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Teaser no pagado (título)',
      defaultValue: 'Tu regulación es un proceso de 12 semanas',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.teaser.description',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Teaser no pagado (descripción)',
      defaultValue: 'Los primeros cambios llegan en 72 horas. Tu primer paso son los próximos 7 días.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.focus.teaser.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Teaser no pagado (CTA)',
      defaultValue: 'Ver tu camino',
      fieldType: 'short',
    },

    // ── FOCUS BANNER — DEFAULT ───────────────────────────────────────
    {
      id: 'mapa.focus.default.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Por defecto (tag)',
      defaultValue: 'TU MAPA EVOLUCIONA',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.default.description.waiting',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Por defecto (esperando desbloqueo)',
      defaultValue: 'Cada semana aparece algo nuevo. Vuelve cuando quieras.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.focus.default.description.complete',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Todo desbloqueado',
      defaultValue: 'Todas las secciones están desbloqueadas. Explora tu mapa completo.',
      fieldType: 'medium',
    },

    // ── EVOLUTION TIMELINE — Milestones ──────────────────────────────
    {
      id: 'mapa.evolution.header',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Encabezado',
      defaultValue: 'Tu mapa evoluciona',
      fieldType: 'short',
      hint: 'Texto que encabeza la línea temporal vertical del mapa.',
    },
    {
      id: 'mapa.evolution.d0.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 0 label',
      defaultValue: 'Tu análisis',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d0.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 0 sublabel',
      defaultValue: '5 dimensiones · Score global',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d3.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 3 label',
      defaultValue: 'Arquetipo del SN',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d3.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 3 sublabel',
      defaultValue: '7 tipos · Tu patrón profundo',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d7.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 7 label',
      defaultValue: 'Insight colectivo',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d7.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 7 sublabel',
      defaultValue: 'Dato nuevo en tu peor dimensión',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d10.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 10 label',
      defaultValue: 'Sesión con Javier',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d10.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 10 sublabel',
      defaultValue: '20 min gratuitos · Sin compromiso',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d14.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 14 label',
      defaultValue: 'Subdimensiones',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d14.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 14 sublabel',
      defaultValue: '2 preguntas · Mayor resolución',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d21.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 21 label',
      defaultValue: 'Extracto del libro',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d21.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 21 sublabel',
      defaultValue: 'Capítulo personalizado',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d30.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 30 label',
      defaultValue: 'Reevaluación',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d30.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 30 sublabel',
      defaultValue: 'Compara con tu día 0',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d90.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 90 label',
      defaultValue: 'Trimestral',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d90.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 90 sublabel',
      defaultValue: 'Evolución a largo plazo',
      fieldType: 'short',
    },

    // ── SESSION ──────────────────────────────────────────────────────
    {
      id: 'mapa.session.title',
      section: 'mapa',
      subsection: 'session',
      label: 'Sesión — título',
      defaultValue: '¿Quieres que Javier revise tu mapa contigo?',
      fieldType: 'short',
      hint: 'Título de la sección de reserva de sesión en el mapa.',
    },
    {
      id: 'mapa.session.description',
      section: 'mapa',
      subsection: 'session',
      label: 'Sesión — descripción',
      defaultValue: '20 minutos. Sin compromiso. Ya tiene tus datos — no repites nada.',
      fieldType: 'medium',
    },

    // ── DIMENSIONS ───────────────────────────────────────────────────
    {
      id: 'mapa.dimension.d1',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión 1 — Regulación',
      defaultValue: 'Regulación',
      fieldType: 'short',
      hint: 'Nombre de la primera dimensión. Aparece en el mapa y en emails.',
    },
    {
      id: 'mapa.dimension.d2',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión 2 — Sueño',
      defaultValue: 'Sueño',
      fieldType: 'short',
    },
    {
      id: 'mapa.dimension.d3',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión 3 — Claridad',
      defaultValue: 'Claridad',
      fieldType: 'short',
    },
    {
      id: 'mapa.dimension.d4',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión 4 — Emocional',
      defaultValue: 'Emocional',
      fieldType: 'short',
    },
    {
      id: 'mapa.dimension.d5',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión 5 — Alegría',
      defaultValue: 'Alegría',
      fieldType: 'short',
    },

    // ── ASPIRACIONAL — 3 fases ───────────────────────────────────────
    {
      id: 'mapa.aspiracional.headline1',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Aspiracional — titular línea 1',
      defaultValue: 'Tu regulación es un proceso de 12 semanas.',
      fieldType: 'short',
      hint: 'Primera línea del titular de la Zona 4 del mapa.',
    },
    {
      id: 'mapa.aspiracional.headline2',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Aspiracional — titular línea 2',
      defaultValue: 'Tu primer paso son los próximos 7 días.',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase1.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 1 — título',
      defaultValue: 'El Despertar',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase1.subtitle',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 1 — subtítulo',
      defaultValue: 'Semanas 1–4 · Reconocer y estabilizar',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase1.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 1 — descripción',
      defaultValue: 'Entenderás qué le pasa a tu biología: neurotransmisores, función hormonal, inflamación. Restaurarás tu sueño con un protocolo diseñado por un médico. En la semana 4, tu primer balance formal confirmará lo que tu cuerpo ya empieza a notar.',
      fieldType: 'long',
    },
    {
      id: 'mapa.aspiracional.fase2.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 2 — título',
      defaultValue: 'La Metamorfosis',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase2.subtitle',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 2 — subtítulo',
      defaultValue: 'Semanas 5–8 · Activar y procesar',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase2.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 2 — descripción',
      defaultValue: 'Desmontarás las creencias y patrones que sostienen el ciclo. Conocerás las partes internas que dirigen tus decisiones sin que lo sepas — el perfeccionista, el controlador, el crítico — y aprenderás a liderarlas. Lo que el burnout congeló empieza a procesarse.',
      fieldType: 'long',
    },
    {
      id: 'mapa.aspiracional.fase3.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 3 — título',
      defaultValue: 'Volar Alto',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase3.subtitle',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 3 — subtítulo',
      defaultValue: 'Semanas 9–12 · Conectar y reconstruir',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase3.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 3 — descripción',
      defaultValue: 'Repararás los vínculos que el burnout dañó, pondrás límites desde tus valores y diseñarás tu nueva arquitectura vital. Un sistema de alertas tempranas para que el burnout no vuelva.',
      fieldType: 'long',
    },
    {
      id: 'mapa.aspiracional.mapNote',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Nota de evolución del mapa',
      defaultValue: 'Tu mapa también evoluciona: cada semana aparece algo nuevo — tu perfil profundo, insights colectivos, reevaluaciones. Vuelve cuando quieras.',
      fieldType: 'medium',
    },

    // ── ASPIRACIONAL — Semana 1 items ────────────────────────────────
    {
      id: 'mapa.aspiracional.week1.item1.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Protocolo de Sueño',
      defaultValue: 'Protocolo de Sueño de Emergencia',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.week1.item1.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Protocolo de Sueño (descripción)',
      defaultValue: 'Diseñado por el Dr. Carlos Alvear. Un plan concreto para ganar hasta una hora más de sueño al día. Resultados en 72 horas.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.aspiracional.week1.item2.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Sesión 1:1',
      defaultValue: 'Sesión 1:1 con Javier A. Martín Ramos',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.week1.item2.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Sesión 1:1 (descripción)',
      defaultValue: 'Director del Instituto Epigenético. Ya tiene tu mapa — la sesión arranca desde tus datos, no desde cero.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.aspiracional.week1.item3.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — MNN©',
      defaultValue: 'Mapa de Niveles de Neurotransmisores (MNN©)',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.week1.item3.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — MNN© (descripción)',
      defaultValue: 'Tu primer análisis bioquímico real: qué sustancias produce tu cerebro, cuáles le faltan y qué significa eso para tu sueño, tu energía y tu claridad mental.',
      fieldType: 'long',
    },
    {
      id: 'mapa.aspiracional.week1.item4.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Garantía',
      defaultValue: 'Garantía total',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.week1.item4.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Garantía (descripción)',
      defaultValue: '7 días. Si no notas mejora en tu sueño, devolución íntegra. Sin preguntas. Sin formularios.',
      fieldType: 'medium',
    },

    // ── ASPIRACIONAL — CTA ───────────────────────────────────────────
    {
      id: 'mapa.aspiracional.preCta',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Pre-CTA — frase emocional',
      defaultValue: 'Tu sistema nervioso lleva años sosteniendo lo que tú no podías soltar. Ahora tienes el mapa.',
      fieldType: 'medium',
      hint: 'Frase en cursiva antes del botón de compra. Voz de Javier.',
    },
    {
      id: 'mapa.aspiracional.delta',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Delta — texto de 72 horas',
      defaultValue: 'Los primeros cambios llegan en 72 horas. No en meses — en 3 días. El Protocolo de Sueño de Emergencia está diseñado para que tu cuerpo note la diferencia antes de que tu mente decida si confía.',
      fieldType: 'long',
    },
    {
      id: 'mapa.aspiracional.ctaButton',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Botón CTA',
      defaultValue: 'Empieza la Semana 1',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.priceCopy',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Sub-copy de precio',
      defaultValue: '97€ · Protocolo de Sueño de Emergencia + Sesión 1:1 con Javier + Mapa de Niveles de Neurotransmisores (MNN©)',
      fieldType: 'medium',
    },
    {
      id: 'mapa.aspiracional.guarantee',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Garantía bajo el precio',
      defaultValue: 'Si tu sueño no mejora en 7 días, te devolvemos los 97€. Sin preguntas.',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.reencuadre',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Reencuadre de precio',
      defaultValue: 'El programa completo tiene tres niveles de acompañamiento desde 2.500€, según la profundidad que necesites. La elección del plan viene después — cuando hayas comprobado con tu propio cuerpo que esto funciona.',
      fieldType: 'long',
      hint: 'Texto que contextualiza el precio de 97€ vs el programa completo.',
    },
    {
      id: 'mapa.aspiracional.reencuadre2',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Reencuadre — cierre',
      defaultValue: 'Por eso existe la Semana 1.',
      fieldType: 'short',
    },
  ]
}
